/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.ventanas;

import edu.cuc.palabras.Palabra;
import java.awt.HeadlessException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JButton;      

/**
 *
 * @author alexisdelahoz
 */
public class FrmPalabras extends javax.swing.JFrame {

    private Palabra palabraNueva;
    private Palabra cantidadsinonimos;

    /**
     * Creates new form FrmPalabras
     */
    public FrmPalabras() {
        initComponents();

        JButton botonesHabilitar[] = {cmdIngresarPalabra};
        JButton botonesDesabilitar[] = {cmdIngresarPalabra1, cmdCantidad, cmdPromedio, cmdMayor};

        edu.cuc.palabras.Palabra.habilitarBotones(botonesHabilitar);
        edu.cuc.palabras.Palabra.deshabilitarBotones(botonesDesabilitar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        cmdIngresarPalabra = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSinonimo = new javax.swing.JTextField();
        cmdIngresarPalabra1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        cmdCantidad = new javax.swing.JButton();
        cmdPromedio = new javax.swing.JButton();
        cmdMayor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Palabras");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese palabra: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 31, -1, -1));

        txtPalabra.setOpaque(false);
        txtPalabra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabraKeyTyped(evt);
            }
        });
        jPanel1.add(txtPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 28, 160, -1));

        cmdIngresarPalabra.setText("Ingresar Palabra");
        cmdIngresarPalabra.setOpaque(false);
        cmdIngresarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarPalabraActionPerformed(evt);
            }
        });
        jPanel1.add(cmdIngresarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 27, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 420, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Sinónimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Ingrese sinónimo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 31, -1, -1));

        txtSinonimo.setOpaque(false);
        txtSinonimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSinonimoKeyTyped(evt);
            }
        });
        jPanel2.add(txtSinonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 28, 160, -1));

        cmdIngresarPalabra1.setText("Ingresar Sinónimo");
        cmdIngresarPalabra1.setOpaque(false);
        cmdIngresarPalabra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarPalabra1ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdIngresarPalabra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 27, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, 420, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        cmdCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/cantidad32x32.png"))); // NOI18N
        cmdCantidad.setText("Cant. Sinonimos");
        cmdCantidad.setFocusable(false);
        cmdCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdCantidad.setOpaque(false);
        cmdCantidad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCantidadActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdCantidad);

        cmdPromedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/promedio32x32.png"))); // NOI18N
        cmdPromedio.setText("Prom. Longitud");
        cmdPromedio.setFocusable(false);
        cmdPromedio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdPromedio.setOpaque(false);
        cmdPromedio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPromedioActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdPromedio);

        cmdMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/mayorque.png"))); // NOI18N
        cmdMayor.setText("Mayor Longitud");
        cmdMayor.setFocusable(false);
        cmdMayor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdMayor.setOpaque(false);
        cmdMayor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMayorActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdMayor);

        jPanel3.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 385, 52));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, 420, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f0348631e7bf65025892797f9890afc4.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdIngresarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarPalabraActionPerformed

        if (txtPalabra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese palabra", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txtPalabra.requestFocusInWindow();
        } else {
            introducirPalabra();

            JButton botonesHabilitar[] = {cmdIngresarPalabra1};
            JButton botonesDesabilitar[] = {cmdIngresarPalabra, cmdCantidad, cmdPromedio, cmdMayor};

            edu.cuc.palabras.Palabra.habilitarBotones(botonesHabilitar);
            edu.cuc.palabras.Palabra.deshabilitarBotones(botonesDesabilitar);
        }

    }//GEN-LAST:event_cmdIngresarPalabraActionPerformed

    private void cmdIngresarPalabra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarPalabra1ActionPerformed

        if (txtSinonimo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Adiccione sinonimo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txtSinonimo.requestFocusInWindow();
        } else {
            introducirSinonimo();

            JButton botonesHabilitar[] = {cmdCantidad, cmdPromedio, cmdMayor};
            JButton botonesDesabilitar[] = {cmdIngresarPalabra, cmdIngresarPalabra1};

            edu.cuc.palabras.Palabra.habilitarBotones(botonesHabilitar);
            edu.cuc.palabras.Palabra.deshabilitarBotones(botonesDesabilitar);  
        }
    }//GEN-LAST:event_cmdIngresarPalabra1ActionPerformed

    private void cmdCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCantidadActionPerformed
        JOptionPane.showMessageDialog(this, "La cantidad de sinonimos es:" + palabraNueva.cantidadSinonimos());


    }//GEN-LAST:event_cmdCantidadActionPerformed

    private void cmdPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPromedioActionPerformed

        JOptionPane.showMessageDialog(this, "El promedio es igual a:" + palabraNueva.promedioLongitud());
    }//GEN-LAST:event_cmdPromedioActionPerformed

    private void cmdMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMayorActionPerformed

        JOptionPane.showMessageDialog(this, "El mayor es:" + palabraNueva.sinonimoMayorLongitud());

        JButton botonesHabilitar[] = {cmdIngresarPalabra, cmdIngresarPalabra1};
        JButton botonesDesabilitar[] = {cmdCantidad, cmdPromedio, cmdMayor};                

        edu.cuc.palabras.Palabra.habilitarBotones(botonesHabilitar);
        edu.cuc.palabras.Palabra.deshabilitarBotones(botonesDesabilitar);
    }//GEN-LAST:event_cmdMayorActionPerformed

    private void txtPalabraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabraKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isLetter(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtPalabraKeyTyped

    private void txtSinonimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSinonimoKeyTyped
       
          char c = evt.getKeyChar();

        if (!Character.isLetter(c)) {
            getToolkit();
            evt.consume();
        }   
        
    }//GEN-LAST:event_txtSinonimoKeyTyped

    private void introducirPalabra() throws HeadlessException {
        palabraNueva = new Palabra(txtPalabra.getText());
        //Caja
        Palabra palabraNueva = new Palabra(txtPalabra.getText());
        txtPalabra.setText(null);
        JOptionPane.showMessageDialog(this,
                "Palabra ingresada en el sistema!",
                "Confirmación",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void introducirSinonimo() throws HeadlessException {

        palabraNueva.adicionarSinonimo(new Palabra(txtSinonimo.getText()));
        txtSinonimo.setText(null);
        JOptionPane.showMessageDialog(this,
                "Sinonimo ingresado en el sistema!",
                "Confirmación",
                JOptionPane.INFORMATION_MESSAGE);           
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPalabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCantidad;
    private javax.swing.JButton cmdIngresarPalabra;
    private javax.swing.JButton cmdIngresarPalabra1;
    private javax.swing.JButton cmdMayor;
    private javax.swing.JButton cmdPromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtPalabra;
    private javax.swing.JTextField txtSinonimo;
    // End of variables declaration//GEN-END:variables
}
